### ISSUE TITLE
Betoj nerodo mano temų, atsakymų, neleidžia kurt temų, atsakius temą jos neberodo

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#141]
^

Gal aš užkeiktas :/
Meta Oi

**Comment by Bebrazmogis** [comment]
```
[2016-02-01 20:26:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/forge/beta.maze.lt/bootstrap/cache/compiled.php:8264
Stack trace:
#0 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(7503): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(7468): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(7460): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(2307): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#5 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 /home/forge/beta.maze.lt/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#9 /home/forge/beta.maze.lt/app/Http/Middleware/CheckIfUsernameValid.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: maze\Http\Middleware\CheckIfUsernameValid->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#12 /home/forge/beta.maze.lt/app/Http/Middleware/CheckIfUserIsBanned.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: maze\Http\Middleware\CheckIfUserIsBanned->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#15 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(12957): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#18 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(11551): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#21 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(12694): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#24 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(12631): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#27 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/forge/beta.maze.lt/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#34 /home/forge/beta.maze.lt/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#35 {main}
```

**Comment by SkepticalHippo** [comment]
Master šitas pataisyta jau. @Bebrazmogis arba @Yiin- sumerginkit master į betą. kthx
